// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2K9U_Oy9mvJF__o1B6SYvWHxp2DwJdyk',
    appId: '1:51362732522:web:da4317884e44cc6dfcba93',
    messagingSenderId: '51362732522',
    projectId: 'breaking-note',
    authDomain: 'breaking-note.firebaseapp.com',
    databaseURL: 'https://breaking-note-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'breaking-note.appspot.com',
    measurementId: 'G-ZJF9WBC3LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfijDVp1ilSy4_cornly_JfivVK6NPdgo',
    appId: '1:51362732522:android:dd4033d216b82385fcba93',
    messagingSenderId: '51362732522',
    projectId: 'breaking-note',
    databaseURL: 'https://breaking-note-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'breaking-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNBXs7CY9vuY4jXNbAkKqEQMr9h7kKeTM',
    appId: '1:51362732522:ios:ec4f0f694aa3608efcba93',
    messagingSenderId: '51362732522',
    projectId: 'breaking-note',
    databaseURL: 'https://breaking-note-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'breaking-note.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNBXs7CY9vuY4jXNbAkKqEQMr9h7kKeTM',
    appId: '1:51362732522:ios:4589b02ac6bc51defcba93',
    messagingSenderId: '51362732522',
    projectId: 'breaking-note',
    databaseURL: 'https://breaking-note-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'breaking-note.appspot.com',
    iosBundleId: 'com.example.firstapp.RunnerTests',
  );
}
